name: Static Analysis

on: ['push', 'pull_request']

jobs:
  pint:
    runs-on: ubuntu-latest

    name: Pint

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: zip
          tools: composer
          coverage: none

      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist --ansi

      - name: Install Pint
        run: composer global require laravel/pint --dev

      - name: Run Pint
        run: pint --test --ansi

  phpstan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dependency-version: [prefer-stable]

    name: PHPStan (${{ matrix.dependency-version }})

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        tools: composer
        coverage: none

    - name: Install Dependencies
      run: |
          composer install --no-interaction --prefer-dist --ansi
          composer require --no-interaction --dev larastan/larastan --ansi

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --no-progress --ansi
